### ISSUE TITLE
Site no longer works offline.

### ISSUE THREAD

**Issue by AwesomeQuest** [theBrianCui/IsMyInternetWorking#1]
Previously, one could save the site on one's own computer to have its functionality available at any time, now however the functionality of the locally saved version is essentially non-existent. I enjoy and appreciate the new features of the new site and would like to have them available locally, as I could before.

**Comment by theBrianCui** [comment]
Hey AwesomeQuest,

Thanks for the note! In version 3, we switched away from inlining styles and JavaScript and thus saving the page to use it offline doesn't work anymore. I didn't intend to break the "offline" functionality because honestly I wasn't aware anyone used the site offline.

So... as a temporary fix, here's a standalone HTML file of v3 that can be opened locally and runs offline!

[index.zip](https://github.com/theBrianCui/IsMyInternetWorking/files/1786104/index.zip)

In the future, I'd like to make the offline version part of the build process so the newest version is always readily available. There's some issues with getting it to work correctly (right now the offline version has to be arranged manually by hand) so that's why we don't have a live offline version yet.

**Comment by AwesomeQuest** [comment]
Wonderful! Thank you very much for both the file and the incredibly quick response!
Have a good day!

**Comment by theBrianCui** [comment]
You're welcome! Thanks for using my website :D
